# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.10
loom_version=1.9-SNAPSHOT

# Mod Properties
mod_version=1.0.1
modLoader=fabric
modid=torchesbt
maven_group=com.enchantedwisp.torchesbt
archives_base_name=torchesbt

# Dependencies
fabric_version=0.107.0+1.21.1
cloth_version=15.0.140

# Compat
trinkets_version=3.9.0
jade_version=15.10.6+fabric
chipped_version=4.0.2